name = "SpectralFittingExtras"
uuid = "1316a2a9-51c4-4e53-bbe9-46a8eba6db52"
authors = ["fjebaker <fergusbkr@gmail.com>"]
version = "0.1.0"

[deps]
SpectralFitting = "f2c56810-742e-4b72-8bf4-27af3bb81a12"
